version: 2
jobs:
  test_regression_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/linear_reg/requirements.txt
            py.test -vv packages/linear_reg/tests
            
workflows:
  version: 2
  test-all:
    jobs:
      - test_regression_model